.TH "belt.h" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
belt.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'clothes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBelt\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
