.TH "belt.cc" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
belt.cc \- This class represents a logical belt\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'belt\&.h'\fP
.br

.SH "Detailed Description"
.PP 
This class represents a logical belt\&. 


.PP
\fBAuthor:\fP
.RS 4
Stephen M\&. Reaves 
.RE
.PP
\fBDate:\fP
.RS 4
July 14th, 2018 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
