.TH "clothes.h" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clothes.h
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClothes\fP"
.br
.RI "\fBClothes\fP abstract class to be used by members of closet\&. Handles the light work\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const int \fBkDummyID\fP = \-1"
.br
.ti -1c
.RI "static const string \fBkDummyName\fP = 'Fake Name'"
.br
.ti -1c
.RI "static const string \fBkDummyPrimColor\fP = 'Fake Primary Color'"
.br
.ti -1c
.RI "static const string \fBkDummySecColor\fP = 'Fake Secondary Color'"
.br
.ti -1c
.RI "static const string \fBkDummyTertColor\fP = 'Fake Tertiary Color'"
.br
.ti -1c
.RI "static const string \fBkDummyPattern\fP = 'Fake Pattern'"
.br
.ti -1c
.RI "static const string \fBkDummyMaterial\fP = 'Fake Material'"
.br
.ti -1c
.RI "static const string \fBkDummyStyle\fP = 'Fake Style'"
.br
.ti -1c
.RI "static const string \fBkDummyLength\fP = 'Fake Length'"
.br
.ti -1c
.RI "static const string \fBkDummyCut\fP = 'Fake Cut'"
.br
.ti -1c
.RI "static const string \fBkDummySleeveLength\fP = 'Fake Sleeve Length'"
.br
.ti -1c
.RI "static const string \fBkDummyCollar\fP = 'Fake Collar'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string kDummyCollar = 'Fake Collar'\fC [static]\fP"

.SS "const string kDummyCut = 'Fake Cut'\fC [static]\fP"

.SS "const int kDummyID = \-1\fC [static]\fP"

.SS "const string kDummyLength = 'Fake Length'\fC [static]\fP"

.SS "const string kDummyMaterial = 'Fake Material'\fC [static]\fP"

.SS "const string kDummyName = 'Fake Name'\fC [static]\fP"

.SS "const string kDummyPattern = 'Fake Pattern'\fC [static]\fP"

.SS "const string kDummyPrimColor = 'Fake Primary Color'\fC [static]\fP"

.SS "const string kDummySecColor = 'Fake Secondary Color'\fC [static]\fP"

.SS "const string kDummySleeveLength = 'Fake Sleeve Length'\fC [static]\fP"

.SS "const string kDummyStyle = 'Fake Style'\fC [static]\fP"

.SS "const string kDummyTertColor = 'Fake Tertiary Color'\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
