.TH "myCloset.h" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
myCloset.h
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <cstring>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'belt\&.h'\fP
.br
\fC#include 'pants\&.h'\fP
.br
\fC#include 'shirt\&.h'\fP
.br
\fC#include 'shoes\&.h'\fP
.br
\fC#include 'socks\&.h'\fP
.br
\fC#include 'vulkan\&.h'\fP
.br
\fC#include 'window\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCloset\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const string \fBkDummyClosetName\fP = 'Fake \fBCloset\fP Name'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const string kDummyClosetName = 'Fake \fBCloset\fP Name'"

.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
