.TH "Ncurses" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ncurses
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ncurses\&.h>\fP
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Stephen M\&. Reaves 
.RE
.PP
\fBDate:\fP
.RS 4
July 14th, 2018 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
