.TH "Shirt" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shirt
.SH SYNOPSIS
.br
.PP
.PP
\fC#include 'shirt\&.h'\fP
.PP
Inherits \fBClothes\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShirt\fP ()"
.br
.ti -1c
.RI "\fBShirt\fP (int id, string name, string prim_color, string sec_color, string tert_color, string pattern, string sleeve_length, string collar)"
.br
.ti -1c
.RI "virtual \fB~Shirt\fP ()"
.br
.ti -1c
.RI "string \fBToXML\fP () const"
.br
.ti -1c
.RI "string \fBToString\fP () const"
.br
.ti -1c
.RI "int \fBGetID\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBid_\fP = \fBkDummyID\fP"
.br
.RI "Global unique identifier\&. "
.ti -1c
.RI "string \fBname_\fP = \fBkDummyName\fP"
.br
.RI "User readable name\&. "
.ti -1c
.RI "string \fBprimary_color_\fP = \fBkDummyPrimColor\fP"
.br
.RI "Primary color\&. "
.ti -1c
.RI "string \fBsecondary_color_\fP = \fBkDummySecColor\fP"
.br
.RI "Secondary color\&. "
.ti -1c
.RI "string \fBtertiary_color_\fP = \fBkDummyTertColor\fP"
.br
.RI "Tertiary color\&. "
.ti -1c
.RI "string \fBpattern_\fP = \fBkDummyPattern\fP"
.br
.RI "Design pattern\&. "
.ti -1c
.RI "string \fBmaterial_\fP = \fBkDummyMaterial\fP"
.br
.RI "Material\&. "
.ti -1c
.RI "string \fBstyle_\fP = \fBkDummyStyle\fP"
.br
.RI "Design style\&. "
.ti -1c
.RI "string \fBlength_\fP = \fBkDummyLength\fP"
.br
.RI "Length of the clothing\&. "
.ti -1c
.RI "string \fBcut_\fP = \fBkDummyCut\fP"
.br
.RI "Cut of the clothing\&. "
.ti -1c
.RI "string \fBsleeve_length_\fP = \fBkDummySleeveLength\fP"
.br
.RI "Length of the sleeve\&. "
.ti -1c
.RI "string \fBcollar_\fP = \fBkDummyCollar\fP"
.br
.RI "Type of collar\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Stephen M\&. Reaves 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shirt::Shirt ()"
Default Constructor 
.SS "Shirt::Shirt (int id, string name, string prim_color, string sec_color, string tert_color, string pattern, string sleeve_length, string collar)"
Parameterized Constructor
.PP
\fBParameters:\fP
.RS 4
\fIid\fP Integer to identify this shirt uniquely across the closet 
.br
\fIname\fP String to identify this shirt to the user 
.br
\fIprim_color\fP Primary color 
.br
\fIsec_color\fP Secondary color 
.br
\fItert_color\fP Tertiary color 
.br
\fIpattern\fP Design pattern 
.br
\fIsleeve_length\fP Length of the sleeve 
.br
\fIcollar\fP Type of collar
.RE
.PP
\fBReturns:\fP
.RS 4
\fBShirt\fP object 
.RE
.PP

.SS "Shirt::~Shirt ()\fC [virtual]\fP"
Deconstructor 
.SH "Member Function Documentation"
.PP 
.SS "int Clothes::GetID ()\fC [inline]\fP, \fC [inherited]\fP"

.SS "string Shirt::ToString () const\fC [virtual]\fP"
ToString 
.PP
\fBReturns:\fP
.RS 4
'string' representing the shirt\&. 
.RE
.PP

.PP
Implements \fBClothes\fP\&.
.SS "string Shirt::ToXML () const"
ToXML 
.PP
\fBDeprecated\fP
.RS 4

.RE
.PP
\fBReturns:\fP
.RS 4
XML representing the shirt\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "string Clothes::collar_ = \fBkDummyCollar\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Type of collar\&. 
.SS "string Clothes::cut_ = \fBkDummyCut\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Cut of the clothing\&. 
.SS "int Clothes::id_ = \fBkDummyID\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Global unique identifier\&. 
.SS "string Clothes::length_ = \fBkDummyLength\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Length of the clothing\&. 
.SS "string Clothes::material_ = \fBkDummyMaterial\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Material\&. 
.SS "string Clothes::name_ = \fBkDummyName\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
User readable name\&. 
.SS "string Clothes::pattern_ = \fBkDummyPattern\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Design pattern\&. 
.SS "string Clothes::primary_color_ = \fBkDummyPrimColor\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Primary color\&. 
.SS "string Clothes::secondary_color_ = \fBkDummySecColor\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Secondary color\&. 
.SS "string Clothes::sleeve_length_ = \fBkDummySleeveLength\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Length of the sleeve\&. 
.SS "string Clothes::style_ = \fBkDummyStyle\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Design style\&. 
.SS "string Clothes::tertiary_color_ = \fBkDummyTertColor\fP\fC [protected]\fP, \fC [inherited]\fP"

.PP
Tertiary color\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
