.TH "Vulkan" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vulkan
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vulkan\&.h>\fP
.PP
Inherits \fBWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVulkan\fP ()"
.br
.ti -1c
.RI "virtual \fB~Vulkan\fP ()"
.br
.ti -1c
.RI "bool \fBInit\fP ()"
.br
.ti -1c
.RI "void \fBDie\fP ()"
.br
.ti -1c
.RI "char \fBMakeWindowChar\fP (string message)"
.br
.ti -1c
.RI "string \fBMakeWindow\fP (string message)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBisInit_\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Vulkan::Vulkan ()"

.SS "Vulkan::~Vulkan ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Vulkan::Die ()\fC [virtual]\fP"

.PP
Implements \fBWindow\fP\&.
.SS "bool Vulkan::Init ()\fC [virtual]\fP"

.PP
Implements \fBWindow\fP\&.
.SS "string Vulkan::MakeWindow (string message)\fC [virtual]\fP"

.PP
Implements \fBWindow\fP\&.
.SS "char Vulkan::MakeWindowChar (string message)\fC [virtual]\fP"

.PP
Implements \fBWindow\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Vulkan::isInit_ = false\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
