.TH "Window" 3 "Sat Jul 14 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP ()"
.br
.ti -1c
.RI "virtual \fB~Window\fP ()"
.br
.ti -1c
.RI "virtual bool \fBInit\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBDie\fP ()=0"
.br
.ti -1c
.RI "virtual char \fBMakeWindowChar\fP (string message)=0"
.br
.ti -1c
.RI "virtual string \fBMakeWindow\fP (string message)=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBisInit_\fP = false"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Window::Window ()"

.SS "virtual Window::~Window ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void Window::Die ()\fC [pure virtual]\fP"

.SS "virtual bool Window::Init ()\fC [pure virtual]\fP"

.SS "virtual string Window::MakeWindow (string message)\fC [pure virtual]\fP"

.SS "virtual char Window::MakeWindowChar (string message)\fC [pure virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "bool Window::isInit_ = false\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
