.TH "window.h" 3 "Thu Jul 19 2018" "ClosetPlusPlus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window.h
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.RI "Abstract class for User Interfaces\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ClosetPlusPlus from the source code\&.
