ClosetPlusPlus: Closet Class Reference
Closet Class Reference
#include "myCloset.h"
Public Member Functions
Closet ()
virtual ~Closet ()
Closes the window, then kills the Closet.
string ToXML () const
string ToString () const
string StoreCloset () const
void ImportCloset (string filename)
This function builds a Closet from a file, then calls the default 'MakeCloset' function.
void MakeCloset ()
This function is the wrapper function that is responsible for creating the clothes and then inserting them to the appropriate map.
string GetClosetName ()
Private Member Functions
Shirt AddShirt ()
Creates a 'Shirt' object.
Pants AddPants ()
Creates a 'Pants' object This function will take user input to record the necessary details for making a new 'Pants'. This function then calls the parameterized constructor for a 'Pants' using those details.
Socks AddSocks ()
Creates a 'Socks' object This function will take user input to record the necessary details for making a new 'Socks'. This function then calls the parameterized constructor for a 'Socks' using those details.
Shoes AddShoes ()
Creates a 'Shoes' object This function will take user input to record the necessary details for making a new 'Shoes'. This function then calls the parameterized constructor for a 'Shoes' using those details.
Belt AddBelt ()
Creates a 'Belt' object This function will take user input to record the necessary details for making a new 'Belt'. This function then calls the parameterized constructor for a 'Belt' using those details.
int AssignID (string type)
Assigns unique ID to clothes This function assigns the next available ID number for a given type. The last two numbers represent the number of the given type, while the other numbers represent the type. For Example, if there are currently 4 shirts, then the next shirt will have the ID of 105. The 100 represents shirts, while the 05 means it is the fifth shirt. This allows for 99 items of a given type and (2^29)-1 types???
Private Attributes
string closet_name_ = kDummyClosetName
map< int, Shirt > shirt_map_
map< int, Pants > pants_map_
map< int, Socks > socks_map_
map< int, Shoes > shoes_map_
map< int, Belt > belt_map_
Ncurses window
Detailed Description
Author
Stephen M. Reaves
Date
July 14th, 2018
Constructor & Destructor Documentation
Closet()
Closet::Closet ()
Default Constructor
~Closet()
Closet::~Closet () virtual
Closes the window, then kills the Closet.
Deconstructor
References window.
Member Function Documentation
AddBelt()
Belt Closet::AddBelt () private
Creates a 'Belt' object This function will take user input to record the necessary details for making a new 'Belt'. This function then calls the parameterized constructor for a 'Belt' using those details.
AddBelt
Returns
An instance of the 'Belt' class.
References AssignID(), and window.
AddPants()
Pants Closet::AddPants () private
Creates a 'Pants' object This function will take user input to record the necessary details for making a new 'Pants'. This function then calls the parameterized constructor for a 'Pants' using those details.
AddPants
Returns
An instance of the 'Pants' class.
References AssignID(), and window.
AddShirt()
Shirt Closet::AddShirt () private
Creates a 'Shirt' object.
AddShirt
Returns
an instance of the 'Shirt' Class. This function will take user input to record the necessary details for making a new 'Shirt'. This function then calls the parameterized constructor for a 'Shirt' using those details.
References AssignID(), and window.
AddShoes()
Shoes Closet::AddShoes () private
Creates a 'Shoes' object This function will take user input to record the necessary details for making a new 'Shoes'. This function then calls the parameterized constructor for a 'Shoes' using those details.
AddShoes
Returns
An instance of the 'Shoes' class.
References AssignID(), and window.
AddSocks()
Socks Closet::AddSocks () private
Creates a 'Socks' object This function will take user input to record the necessary details for making a new 'Socks'. This function then calls the parameterized constructor for a 'Socks' using those details.
AddSocks
Returns
An instance of the 'Socks' class.
References AssignID(), and window.
AssignID()
int Closet::AssignID (string type) private
Assigns unique ID to clothes This function assigns the next available ID number for a given type. The last two numbers represent the number of the given type, while the other numbers represent the type. For Example, if there are currently 4 shirts, then the next shirt will have the ID of 105. The 100 represents shirts, while the 05 means it is the fifth shirt. This allows for 99 items of a given type and (2^29)-1 types???
AssignID
Parameters
type A string dictating the type of clothing to check.
Returns
An integer corrosponding to the next available ID for the given type, or -1 for an error.
Note
So far the types are hard coded in. Meaning you can only create clothes that are either shirts, pants, belts, socks, or shoes. There is currently no way to dynamically add types. Underwear types were intentionally left out to test the best way to dynamically add new types.
<
Todo:
Use Switch-case for Closet::AssignID
References belt_map_, pants_map_, shirt_map_, shoes_map_, socks_map_, and window.
GetClosetName()
string Closet::GetClosetName ()
GetClosetName
Returns
Name of the closet
References closet_name_.
ImportCloset()
void Closet::ImportCloset (string filename)
This function builds a Closet from a file, then calls the default 'MakeCloset' function.
ImportCloset
Note
The filename must end in an acceptable filetype
MakeCloset()
void Closet::MakeCloset ()
This function is the wrapper function that is responsible for creating the clothes and then inserting them to the appropriate map.
MakeCloset For each type of clothing, this function asks the user if they want to add a new clothing of that type. If they do then they call the clothing function to fill in the clothing specific details. This function calls on 'Window' to handle the input.
References AddBelt(), AddPants(), AddShirt(), AddShoes(), AddSocks(), belt_map_, closet_name_, Clothes::GetID(), pants_map_, shirt_map_, shoes_map_, socks_map_, and window.
StoreCloset()
string Closet::StoreCloset () const
StoreCloset
Returns
XML representation of closet
References belt_map_, pants_map_, shirt_map_, shoes_map_, and socks_map_.
ToString()
string Closet::ToString () const
ToString
Returns
'string' representing the closet
References belt_map_, pants_map_, shirt_map_, shoes_map_, and socks_map_.
ToXML()
string Closet::ToXML () const
Member Data Documentation
belt_map_
map<int, Belt> Closet::belt_map_ private
closet_name_
string Closet::closet_name_ = kDummyClosetName private
pants_map_
map<int, Pants> Closet::pants_map_ private
shirt_map_
map<int, Shirt> Closet::shirt_map_ private
shoes_map_
map<int, Shoes> Closet::shoes_map_ private
socks_map_
map<int, Socks> Closet::socks_map_ private
window
Ncurses Closet::window private
The documentation for this class was generated from the following files:
myCloset.h
myCloset.cc